//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceEmpresa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/WcfServices")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEmpresa.IServiceEmpresa")]
    public interface IServiceEmpresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpresa/Registro", ReplyAction="http://tempuri.org/IServiceEmpresa/RegistroResponse")]
        WebApp.ServiceEmpresa.Empresa Registro(WebApp.ServiceEmpresa.Empresa obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpresa/Registro", ReplyAction="http://tempuri.org/IServiceEmpresa/RegistroResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceEmpresa.Empresa> RegistroAsync(WebApp.ServiceEmpresa.Empresa obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpresa/Listar", ReplyAction="http://tempuri.org/IServiceEmpresa/ListarResponse")]
        WebApp.ServiceEmpresa.Empresa[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEmpresa/Listar", ReplyAction="http://tempuri.org/IServiceEmpresa/ListarResponse")]
        System.Threading.Tasks.Task<WebApp.ServiceEmpresa.Empresa[]> ListarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEmpresaChannel : WebApp.ServiceEmpresa.IServiceEmpresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEmpresaClient : System.ServiceModel.ClientBase<WebApp.ServiceEmpresa.IServiceEmpresa>, WebApp.ServiceEmpresa.IServiceEmpresa {
        
        public ServiceEmpresaClient() {
        }
        
        public ServiceEmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApp.ServiceEmpresa.Empresa Registro(WebApp.ServiceEmpresa.Empresa obj) {
            return base.Channel.Registro(obj);
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceEmpresa.Empresa> RegistroAsync(WebApp.ServiceEmpresa.Empresa obj) {
            return base.Channel.RegistroAsync(obj);
        }
        
        public WebApp.ServiceEmpresa.Empresa[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<WebApp.ServiceEmpresa.Empresa[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
    }
}
